### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by benmed00** [shaukinkhan477/Newsletter-Creator-App#19]
- Implement the docker files
- Add the `.yml` file config
- Add screen-shots for the process

**Comment by benmed00** [comment]
Below is a **Docker Compose** setup for deploying an **Angular frontend** and a **Node.js backend** with **Docker**.

---

## **📌 Project Structure**
Ensure your project is structured as follows:
```
/my-project
│── /frontend        (Angular project)
│── /backend         (Node.js project)
│── docker-compose.yml
│── .dockerignore
```

---

## **📌 Step 1: Create Dockerfiles for Each Service**
### **1️⃣ Dockerfile for Angular (Frontend)**
Create a `Dockerfile` inside the `/frontend` directory.

```dockerfile
# Stage 1: Build the Angular app
FROM node:20 AS build

WORKDIR /app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy the entire app
COPY . .

# Build the Angular project
RUN npm run build --prod

# Stage 2: Serve with Nginx
FROM nginx:1.25

WORKDIR /usr/share/nginx/html

# Remove default Nginx static content
RUN rm -rf ./*

# Copy built Angular files from the build stage
COPY --from=build /app/dist/your-angular-app . 

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

### **2️⃣ Dockerfile for Node.js (Backend)**
Create a `Dockerfile` inside the `/backend` directory.

```dockerfile
# Use Node.js base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the backend port
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]
```

---

## **📌 Step 2: Create an Nginx Configuration for Angular**
Create a `nginx.conf` file inside `/frontend`:

```nginx
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    error_page 404 /index.html;

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf|mp4|webm)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
```
🔹 This ensures the **Angular frontend** serves API requests via `/api/` to the **Node.js backend**.

---

## **📌 Step 3: Create `docker-compose.yml`**
Create a `docker-compose.yml` file in your project root:

```yaml
version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  app-network:
    driver: bridge
```

---

## **📌 Step 4: Create a `.dockerignore` File**
Inside `/frontend` and `/backend`, create a `.dockerignore` file to reduce build size:

```
node_modules
dist
.git
Dockerfile
docker-compose.yml
```

---

## **📌 Step 5: Build and Deploy**
Run the following command from the **root of your project**:

```sh
# Build the containers
docker-compose build

# Start the services
docker-compose up -d
```

---

## **📌 Step 6: Verify Deployment**
- Access **Frontend**: `http://localhost`
- Access **Backend**: `http://localhost:3000/api`

---

## **📌 Additional Improvements**
✅ **Docker Volumes**: Add volumes for persistent storage.  
✅ **Production Optimization**: Use **Alpine Linux** base images for smaller containers.  
✅ **Reverse Proxy**: Use **Traefik** or **Caddy** for advanced routing.  

This setup **fully containers your Angular + Node.js stack** and makes deployment easy! 🚀
